services:
  - type: web
    name: django-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        value: django-insecure-d+j2xsj=qo2vfiybnz8xi1))=z@7wg3w=pg%*bf3m!(gswl=04
      - key: DEBUG
        value: 'False'
