# Generated by Django 5.2 on 2025-06-25 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='timestamp',
            new_name='created',
        ),
    ]
